using System;

namespace GoogleGeocodingApi
{
	public enum AddressType
	{
		UNKOWN,
		STREET_ADDRESS,
		ROUTE,
		INTERSECTION,
		POLITICAL,
		COUNTRY,
		ADMINISTRATIVE_AREA_LEVEL_1,
		ADMINISTRATIVE_AREA_LEVEL_2,
		ADMINISTRATIVE_AREA_LEVEL_3,
		ADMINISTRATIVE_AREA_LEVEL_4,
		ADMINISTRATIVE_AREA_LEVEL_5,
		COLLOQUIAL_AREA,
		LOCALITY,

		SUBLOCALITY,
		SUBLOCALITY_LEVEL_1,
		SUBLOCALITY_LEVEL_2,
		SUBLOCALITY_LEVEL_3,
		SUBLOCALITY_LEVEL_4,
		SUBLOCALITY_LEVEL_5,

		NEIGHBORHOOD,
		PREMISE,
		SUBPREMISE,
		POSTAL_CODE,
		NATURAL_FEATURE,
		AIRPORT,
		UNIVERSITY,
		PARK,
		POINT_OF_INTEREST,
		ESTABLISHMENT,
		BUS_STATION,
		TRAIN_STATION,
		TRANSIT_STATION,
		CHURCH,
		FINANCE,
		POST_OFFICE,
		PLACE_OF_WORSHIP,	
	}
}

